version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: trading-journal-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/trading-journal
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - websocket

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: websocket-server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/trading-journal
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
