# Utiliser une image de base Node.js
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port du serveur WebSocket
EXPOSE 4000

# Démarrer le serveur WebSocket
CMD ["node", "websocket/websocketServer.js"]